### ISSUE TITLE
How to add a system dependency?

### ISSUE THREAD

**Issue by thomas-huegel** [pwm/nixkell#30]
Hi pwm,
I enjoy using your framework, as it makes life so easier with Haskell and Nix.
However, I wonder if there is a simple way to add a system dependency (like `zlib`) to a project.
The equivalent of `nix-shell -p zlib`.
Thanks a lot for your work!

**Comment by pwm** [comment]
Hi @thomas-huegel and thanks for your kind words!

> I wonder if there is a simple way to add a system dependency (like zlib) to a project.

Just add `zlib` to [tools](https://github.com/pwm/nixkell/blob/0315a721d4/nixkell.toml#L11-L21). This change should be picked up automatically by direnv which will then rebuild your shell. After that `zlib` should be available eg. in `LD_LIBRARY_PATH` as a result of [this](https://github.com/pwm/nixkell/blob/0315a721d4/shell.nix#L10)

**Comment by thomas-huegel** [comment]
Ok, thank you!
