### ISSUE TITLE
Adding outside dependencies to a project 

### ISSUE THREAD

**Issue by Elland** [pwm/nixkell#7]
First, thanks for this. 

After struggling with reproducible builds across different machines and systems for way too long, I decided to pull the trigger and finally try out nix. As everyone knows, that’s a difficult road to travel and projects such as these help lowering the barrier to entry. 

Now as a nix newbie, I have a question I wasn’t able to figure out in the docs. The project has a `packages.nix` and a `packages` folder inside, but I’m unsure how to proceed with them. 

Let’s say I want to add a dependency to my project that nix can’t build (marked as broken or not even available) but I can download the tarball from hackage. How would one go about adding such a dependency to their project?

On a similar note, if I need to fork a package, what about using a git link?

Both of those are feasible with stack but I’m not sure how to go about it using Nixkell. 

Thanks in advance :)

**Comment by pwm** [comment]
Hey @Elland, first of all apologies for the long radio silence, the real world has caught up with me a bit lately...

Great question! It's something I should definitely address in the readme now that I will have a bit more time again.

The easiest way to do that is using `cabal2nix` (add it to the tools in `nixkell.toml`).

To get something from hackage:
```
cabal2nix cabal://<my-package>-1.2.3.4 > nix/packages/<my-package>.nix

To get it from github:
```
cabal2nix git@github.com:myself/mylib.git > nix/packages/mylib.nix
```

Once the above is done just run `direnv reload` and nix should get those packages. This works thanks to [packagesFromDirectory](https://github.com/NixOS/nixpkgs/blob/54d306ae9a5e53147dfa56ee2530aeb0da638b89/pkgs/development/haskell-modules/lib.nix#L391-L392) which we use in `packages.nix`.

You can then tweak things further in the `manual` section of `ourHaskell` in `package.nix`, eg. you could say:
```
mylib = pkgs.haskell.lib.doJailbreak(hprev.mylib);
```
to remove version bound checks.

With the current way nixkell is set up I think the above is the simplest way to achieve what you want. Another way would be to do it without executing `cabal2nix` and storing the resulting derivation under `nix/packages`. This would mean doing the following in `manual`:
```
mylib = hprev.callCabal2nix "mylib"
  (builtins.fetchGit {
    url = git@github.com:myself/mylib.git;
    rev = ...;
  })
  { };
```
You could also use `callHackageDirect` instead of `fetchGit` to get it from Hackage.

Hope this helps!

**Comment by Elland** [comment]
Thanks @pwm, that was super helpful!
